spring.application.name=smart-field
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/smartfield
spring.datasource.username=postgres
spring.datasource.password=adinath
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jackson.serialization.write-dates-as-timestamps=false
